### ISSUE TITLE
Validation on survey when creating new inspection

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#118]
If the inspection configuration is not set up for the target risk level, the API fail the transaction of putting it to ready status.
Ex: create an inspection for a risk level not configured.

**Comment by iamkinetic** [comment]
J'ai aussi corrigé ce bug dans ma branche

Sent from my iPhone

On Aug 23, 2018, at 9:42 AM, Phil <notifications@github.com<mailto:notifications@github.com>> wrote:


If the inspection configuration is not set up for the target risk level, the API fail the transaction of putting it to ready status.
Ex: create an inspection for a risk level nont configured or without survey
