### ISSUE TITLE
Add imported fields to entities which will be used in importation process

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#163]
Ajouter une classe abstraite BaseImportedModel qui héritera de BaseModel et qui aura ces champs supplémentaires :
o IdExtern : string
o ImportedOn : dateTime?
o HasBeenModified : bool
Tous les modèles qui seront importés hériteront désormais de cette nouvelle classe abstraite plutôt que de BaseModel.

Créer la migration.

Et on modifie tous les services pour que l'ajout, la suppression et la modification renseignent HasBeenModified).

**Comment by iamkinetic** [comment]
J'ai remarqué dans quelques tables que le champ ImportedOn est à "000-01-01 00:00:00" (ce qui est la date "erreur" de MySql")  :

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/55bc3c44-577f-4cdd-83f0-329f8a14ef6e)

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/b3bd0bc9-e4fc-4873-92a5-f9f7338f73d9)

Puis on peut voir dans la configuration des tables que c'est la valeur par défaut :

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/8e378191-09eb-41d4-b4c6-192f7a053f1d)

Il faut s'assurer qu'il n'y ait pas de valeur par défaut ou qu'elle soit nulle pour ne pas avoir de 0000-01-01 en BD.

**Comment by iamkinetic** [comment]
Le problème est que la date d'importation n'est pas "nullable".  Il faut qu'elle soit "nullable" parce que même si un entity est importable, ça ne veut pas dire qu'il sera importé.
