### ISSUE TITLE
la désactivation du questionnaire ne désactive pas ses collections enfant.

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#180]
Ce point ne cause aucune erreur dans l'affichage car un questionnaire n'est pas réactivable.
Lorsque l'on supprime un questionnaire celui-ci est desactivé par le CrudService, cependant ce dernier ne descends pas en récursive dans les enfants de l'entité.
Modifications: 
 - Surcharger la fonction remove dans le service SurveyService
     -> Désactiver les entités suivantes:
               - survey_localization
               - survey_question
               - survey_question_localization
               - survey_question_choice
               - survey_question_choice_localization

**Comment by iamkinetic** [comment]
Ce n'est pas nécessaire que les enfants soient nécessairement désactivés lorsqu'on désactive le parent.  Il n'y a aucun gain quelconque à faire.
