### ISSUE TITLE
Add validation on imported data field type

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#204]
The import failed with null value due to field type problem comparison before the controller.
Ex:
 Hazardous material will fail if we pass a string in parameter boolean "react_to_water"
like: "1", True, False, "Oui", Oui, ...
 -> The json converter will not find the riight model and will send a null object.

**Comment by iamkinetic** [comment]
We'll wait until all importation's issues are done before moving to this one.
