### ISSUE TITLE
Ajuster la taille des champs floor, wall, sector aux limitations du mobile

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#214]
Ces contrôles étant limités dans le formulaire du mobile il faudrait répliquer ces contraintes aux imports et à la BD.
floor -> 3
wall et sector sont des listes qui ne contiennent pour le moment que 3 caractères max

Tables concernées:
 BuildingAlarmPanel, BuildingSprinkler, BuildingHazardousMaterial(ainsi que les tables d'inspection liées)

**Comment by iamkinetic** [comment]
Les risques particuliers?

**Comment by iamkinetic** [comment]
Fait dans #211.

**Comment by philipperobertgh** [comment]
Il manque les matières dangereuses .
