### ISSUE TITLE
Add fire safety department logo to the report configuration tool

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#264]
* Make logo available in the reporting configuration's tool.

**Comment by iamkinetic** [comment]
Attention, ça corrige aussi :
* cauca-9-1-1/survip#464 : le checkBox "par défaut" qui n'est pas correctement sauvegardé.
* cauca-9-1-1/survip#463 : images qui ne s'impriment pas dans le rapport.

**Comment by iamkinetic** [comment]
Testeur, cette inspection (en DEV) contient des images dans le plan, les risques particuliers et les anomalies:

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/64595ddb-55aa-4042-a804-0bc138c483da)
