### ISSUE TITLE
Information pour l'importation No 1 (liste SSI et données a conserver)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-webapi#265]
Liste SSI ...

* [x] MRC Coaticook (au complet: Beecher-Falls, Waterville, Coaticook, Compton)
* [x] SSI Sutton 
* [x] SSI Lac Brome
* [x] SSI Sainte-Anne-des-Lacs
* [x] MRC Rouville (au complet: Saint-Mathias-Sur-Richelieu, Saint-Paul-D'abbotsford, Ange-Gardien, Marieville, Richelieu, Rougemont, Saint-Césaire, Saint-Angèle-de-Monnoir)
* [x] MRC Maskoutains (au complet: Saint-Liboire, Régie Louis-Aimé-Massue, Saint-Marcel-De-Richelieu, Sainte-Pie, Saint-Hyacinthe, Saint-Valérien-de-Milton, SSI Nord Des Maskoutains, Saint-Damase, Saint-Dominique, Sainte-Hélène-de-Bagot, Sainte-Madeleine, Saint-Jude)

Données a conserver ...

1. Questionnaires

**Comment by iamkinetic** [comment]
@jocelyncardinal Je commence à voir que c'est pas mal de SSI!  Est-ce qu'on a vraiment besoin de tout ça?

**Comment by jocelyncardinal** [comment]
Oui, pour projets-pilotes ...

MRC Coaticook (au complet: Beecher-Falls, Waterville, Coaticook, Compton)
SSI Sutton
SSI Lac Brome
SSI Sainte-Anne-des-Lacs

**Comment by jocelyncardinal** [comment]
Pour MRC Rouville et MRC Maskoutains ca peu attendre ...

**Comment by iamkinetic** [comment]
Bon, tout est transféré (avec un *).

**Comment by jocelyncardinal** [comment]
Il manque les SSIs ... 
![capture d ecran 2019-01-29 a 16 44 11](https://user-images.githubusercontent.com/32175949/51942514-41cdcc80-23e5-11e9-9280-354199e96e50.png)

**Comment by iamkinetic** [comment]
En effet!  Je n'ai pas accès à quoi que ce soit du bureau de chez nous, donc je regarderai ça demain matin.

**Comment by jocelyncardinal** [comment]
Oui , pas de problème du tout :)

Le 29 janv. 2019 à 18:44, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


En effet! Je n'ai pas accès à quoi que ce soit du bureau de chez nous, donc je regarderai ça demain matin.

**Comment by jocelyncardinal** [comment]
je ne vois pas le SSI Lac Brome …

**Comment by jocelyncardinal** [comment]
L'importation des nom et prénom "mergé" ensemble ...

![img_0903](https://user-images.githubusercontent.com/32175949/52087264-e6334880-2576-11e9-9add-8bc8b83078de.jpg)

**Comment by jocelyncardinal** [comment]
**Plus capable d'approuvé une inspection ...**

![capture d ecran 2019-01-31 a 16 37 27](https://user-images.githubusercontent.com/32175949/52087409-5c37af80-2577-11e9-9522-ef456baccd79.png)
![capture d ecran 2019-01-31 a 16 37 39](https://user-images.githubusercontent.com/32175949/52087410-5c37af80-2577-11e9-8d4e-75eb9082194e.png)
