### ISSUE TITLE
Version 1.4.2 issues

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-webapi#267]
* [x] Call des liste des bâtiments qui 500 parce que l'usager assigné est nul.
* [x] L'ajout d'une configuration par niveau de risque fail badly à la sauvegarde.

**Comment by Jeepsboucher** [comment]
Dans Gestion des questionnaires, lorsqu'on ajoute une question à un questionnaire, l'erreur se produit seulement à la première question.
Toujours dans Gestion des questionnaires, lorsqu'on modifie un question, si on clique sur l'une des deux flèches sans avoir sélectionné une question auparavant.
Dans Gestion des villes, onglet Ville, lorsqu'on ajoute/modifie une ville, on peut écrire plus de 3 chiffres dans le code à 3 chiffre, cela produit une erreur.
Dans Gestion des villes, onglet Ville, lorsqu'on ajoute/modifie une ville, on peut écrire un code trop long pour l'emplacement, cela produit une erreur (10 caractères passent, mais 11 non)
Dans Gestion des villes, onglet Région, on peut encore ajouter un code trop long (Voir le bug plus haut)
Dans Gestion des villes, onglet Province, on peut encore ajouter un code trop long (Comme celui du dessus)
Dans Gestion des villes, onglet Pays, les deux codes à entrer n'ont pas de limite.
Dans Gestion système, lorsqu'on ajoute un utilisateur, on ne voit pas les critères pour le mot de passe
Dans Gestion système lorsqu'on ajoute un utilisateur, le mot de passe n'est pas caché dans le champ de confirmation
Dans Gestion système, onglet SSI, lorsqu'on clique sur ajouter un call get se fait à l'API, mais il est toujours null.

**Comment by iamkinetic** [comment]
#447 created for the fire safety department's issues.
#446 created for the max length validation's issues.

There is already an issue for both of those user's management issues.

**Comment by iamkinetic** [comment]
@jocelyncardinal Les deux bugs mentionnés dans la description de ce point ont été réglé et seront released éventuellement (je te dirai lorsque ce sera fait).  

Les points rentrés par @jeepsboucher n'ont pas été corrigé, mais j'ai créé des nouveaux points pour qu'on les check plus tard.

**Comment by iamkinetic** [comment]
@jocelyncardinal FYI le processus de mise à jour est en branle.  Probablement que d'ici 30 minutes ce sera complété.  Je vérifierai ça à mon retour demain matin.

**Comment by iamkinetic** [comment]
@jocelyncardinal Ils m'ont dit qu'il ferait ça hier avant de partir, mais ça clairement pas été fait.  Les techs ne sont pas encore arrivé ce matin, je vais les relancer à leur arrivée.
