### ISSUE TITLE
Cannot approve an inspection anymore

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-webapi#269]
**Describe the bug**
Cannot approve an inspection anymore

**Screenshots**
![capture d ecran 2019-01-31 a 16 37 27](https://user-images.githubusercontent.com/32175949/52091290-eb49c500-2581-11e9-8f5e-267e4bb031e5.png)

![capture d ecran 2019-01-31 a 16 37 39](https://user-images.githubusercontent.com/32175949/52091294-ef75e280-2581-11e9-93b3-fbbf838361ff.png)

**Comment by jocelyncardinal** [comment]
Related to issue 265

**Comment by iamkinetic** [comment]
Error code 500 from https://survipreventiontest.cauca.ca/api/Inspection/(*)/approve

**Comment by iamkinetic** [comment]
Ouin, celui-là semble être un bug qui n'a pas été causé par la mise à jour des librairies qu'on utilise.

Je ne comprends pas trop ce qui se passe avec ça, mais je travaille là dessus.

**Comment by iamkinetic** [comment]
Ok pour l'historique le problème est celui-ci
* Nous avons utilisés le property hiding dans l'héritage d'une des classes pour réussir à faire quelque chose de spécifique à l'importation.
* Nous utilisons également la "reflection" à quelques endroits dans le code de l'acceptation d'inspection pour avoir du code générique.  La reflection retourne la propriété qui est cachée ET la propriété qui la cache au lieu de juste celle qui la cache.
* Comme le property hiding n'est pas exactement une très bonne pratique, je vais remplacer ça par une meilleure méthode (ie: contraintes de généricité via interface plutôt que par classe abstraite générique).

Pour le détail, c'est cette ligne de `InspectionBuilding` qui est la cause du problème:
```
public new ICollection<InspectionBuildingLocalization> Localizations { get; set; }
```
Je crois bien que ça été ajouté comme un genre de workaround pour faciliter l'héritage dans l'importation.  La solution exacte était d'enlever cette ligne pour ne plus cacher la vraie propriété et de changer les contraintes de généricités des `BaseBuildingContact`, `BaseBuildingHazardousMaterial` et compagnie de `BaseBuilding` à `IBaseBuilding` (que je viens de créer à partir de `BaseBuilding`).

C'est définitivement un problème que je qualifierais de niveau avancé.

**Comment by iamkinetic** [comment]
Ok, la correction est terminée et les techs m'ont dit que l'API serait mis à jour d'ici midi.

**Comment by iamkinetic** [comment]
Ok, c'est fait, la correction est en ligne.

**Comment by jocelyncardinal** [comment]
Ok merci …

Par contre je vois plus le bouton pour générer le rapport PDF ? Pas capable d’ajouter cette colonne

[cid:image001.png@01D4BA24.B9730960]

De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip-webapi <reply@reply.github.com>
Date : vendredi 1 février 2019 11:47
À : CAUCA-9-1-1/survip-webapi <survip-webapi@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip-webapi] Cannot approve an inspection anymore (#269)


Ok, c'est fait, la correction est en ligne.

**Comment by iamkinetic** [comment]
Il y a un workaround pour ça.  Dans ton browser, tu peux aller dans la console et coller cette commande :

```
localStorage.setItem("column-visible-mode3", "[false,true,true,true,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,true]")
```

Ce site montre comment afficher la console dans Safari sur Mac : 
https://www.wickedlysmart.com/hfjsconsole/

La commande devrait te retourner "Undefined" comme ceci :
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/8c894fec-861d-4ef1-98c4-5c3a3b5d7ce7)

Après ça tu peux faire un refresh du browser et la colonne va s'afficher.
