### ISSUE TITLE
Manage locationType for Coordinates in webAPI

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#281]
As the coordinates are always visible in the firehydrant configuration, we have to remove or change it from the enum.

**Comment by iamkinetic** [comment]
Ce point devrait être fait dans CAUCA-9-1-1/survip#415, non?

**Comment by philipperobertgh** [comment]
ben le 415 c'est le point du web donc non. Mais il faut preciser lors du pullrequest qu'on doit faire celui de l'api d'abord, c'est ce que l'on fait d'habitude, c'est un point que j'ai créé suite à la question de Jean-Philippe sur l'enum.

**Comment by iamkinetic** [comment]
Je ne comprends pas vraiment comment vous avez pu faire #415 sans avoir d'abord fait les ajustements dans l'enum??

**Comment by philipperobertgh** [comment]
Lié au #415
