### ISSUE TITLE
Problem with inspection completion

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#305]
* [x] Fire protection are not transferred to building tables on complete inspection
* [x] Anomaly and particular risks are not completely transferred to building tables(link between entities tables picture and picture table is missing)-> cause error in API.
* [x] Validate if the other values are correctly set from completion

**Comment by iamkinetic** [comment]
Je pense que c'est la fenêtre d'acceptation qui ne load plus les sections du bas.

**Comment by iamkinetic** [comment]
Deux problèmes:
* Une fonction du InspectionBuildingController a été enlevé par toi ce qui faisait qu'on ne pouvait plus compléter.
* Les sections du bâtiments ne se loadait plus correctement dans l'approbation.
