### ISSUE TITLE
Picture linked problem on inspection approval

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#311]
When approving inspection from the web page, the link of the pictures will be lost if the building had pictures before the inspection and those are not modified during the inspection.

**Comment by philipperobertgh** [comment]
@jocelyncardinal Ce problème arrive actuellement et sera corrigé dès que la nouvelle version sera disponible.
Uniquement si l'image n'a pas changée dans l'inspection.

**Comment by jocelyncardinal** [comment]
D’accord merci pour l’info. J’avais déjà remarqué quon pouvais perdre l’image (plan implantation) lors de l’approbation mais j’étais pas capable de reproduire le symptôme systématiquement. Je crois que tu as mis le doigt sur le bobo - Uniquement si l'image n'a pas changée dans l'inspection. Good job !


Le 29 mars 2019 à 10:12, Phil <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jocelyncardinal<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjocelyncardinal&data=02%7C01%7C%7C08ddfdf2afde499a6a4d08d6b4509c66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636894655639795950&sdata=oVF08BWLFgaAJ8vBVg0Xm5j%2BIDJ3t4vP3m6Ws%2Bn5ezg%3D&reserved=0> Ce problème arrive actuellement et sera corrigé dès que la nouvelle version sera disponible.
Uniquement si l'image n'a pas changée dans l'inspection.
