### ISSUE TITLE
Setup odata et refaire les call du tableau de bord pour l'utiliser

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-webapi#68]

**Comment by iamkinetic** [comment]
@mickjol      
Avant de trop m'avancer là-dedans, j'aimerais que tu essaies ce que j'ai de fait.   

J'ai refait la requête qui sort les bâtiments sans inspection avec OData. J'ai séparé l'adresse en deux champs (FullLaneName et FullCivicNumber).  L'url temporaire est celui ci :

http://localhost:5555/api/Inspection/BuildingWithoutInspectionOData

Ça fonctionne bien dans mes tests, mais j'utilise Postman pour mes tests :

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/e6109cb8-071e-48a7-9467-3db71e8e9523)

**Comment by iamkinetic** [comment]
Bref, si ça marche pour l'onglet "Bâtiment", je pourrai compléter les requêtes manquantes.

**Comment by iamkinetic** [comment]
Et ça peut clairement attendre avant d'être fait.

**Comment by mickjol** [comment]
En utilisant ton URL comme plus haut, ca fonctionne : /api/Inspection/BuildingWithoutInspectionOData?$filter=contains(tolower(fullLaneName),tolower('dionne'))&$orderby=fullCivicNumber

Par contre, j'ai fait le test dans l'application. Devexpress génère le URL suivant :
/api/Inspection/BuildingWithoutInspectionOData?%24top=20&%24count=true

**Comment by iamkinetic** [comment]
Ok, le standard OData est que lorsqu'on demande un count ($count=true), ça retourne l'object dans ce format :  

{
    "@odata.context": "http://localhost:5555/api/odata/$metadata#BuildingForDashboard",
    "@odata.count": 14398,
    "value": [
        {
            "Id": "0005fa81-2350-4d1d-ac38-6e918cb42a6d",
            "IdRiskLevel": "dc964b02-389c-4b8d-9b5b-f7d7a6502d5b",
            "FullLaneName": "2E AVENUE"
       }]
}

Ça semble être supporté par DevExtreme selon ma rapide recherche (https://www.devexpress.com/Support/Center/Question/Details/T395481/response-body-for-count-request).

Le problème que tu avais est que l'URL original utilisait un controller Asp.net core standard avec le routing standard qui ne supportait pas au complet les requêtes odata.  J'ai refait un controller OData avec un routing OData et avec celui-ci on reçoit la réponse attendue : 

http://localhost:5555/api/odata/BuildingForDashboard?%24top=20&%24count=true

**Comment by philipperobertgh** [comment]
**Important :** 
**Valider les appels de requêtes pour que la recherche de données soit accent et case insensitive.**

**Comment by iamkinetic** [comment]
Ok, tous les calls sont maintenant là, tu peux switcher le tableau de bord à OData.

**Comment by iamkinetic** [comment]
J'ai mis le pull request à ton nom dans le webapi.

**Comment by iamkinetic** [comment]
J'ai fermé temporairement le pull request.

Peut-être que tu pourras starter de l'api de la branche #67 au lieu de la #68.  La #67 est fait par dessus là #68 et elle contient des changements qu'il faudra faire anyway :
* Colonne de coordinates en type Geography au lieu de string.
