### ISSUE TITLE
Enlever les méthodes non implémentées de l'API

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-webapi#76]
Plusieurs méthodes sont non implémentées dans l'API, souvent à cause des méthode abstraite du BaseCrudService (Get(id), GetList()). Même si ces méthodes ne sont appelées que dans l'API test, il faut y apporter des validations pour que celle-ci ne causent pas d'erreur.
Modification:
 - Ajouter un autre service BaseCrudServiceWithGet avec ces méthodes abstraite et modifier l'existant pour les enlever

**Comment by iamkinetic** [comment]
Absolument d'accord avec l'idée de faire un BaseCrudServiceWithGet
